#`version: '3.8'

services:

  management:
    image: obulka/mysql-cluster
    #command: ndb_management
    #Default options are read from the following files in the given order:
    #/etc/my.cnf /etc/mysql/my.cnf /usr/local/mysql/etc/my.cnf ~/.my.cnf
    command: ndb_mgmd --initial --config-file /var/lib/mysql-cluster/cluster.ini --ndb-nodeid=1
    volumes:
      - ./configs/cluster.ini:/etc/mysql-cluster.cnf

    networks:
      - mysql_cluster


  data1:
    image: obulka/mysql-cluster
    depends_on:
      - "management"
    command: ndbd --ndb-nodeid=2
    volumes:
      - ./configs/node.ini:/etc/my.cnf
    networks:
      - mysql_cluster

  data2:
    image: obulka/mysql-cluster
    depends_on:
      - "management"
    command: ndbd --ndb-nodeid=3
    volumes:
      - ./configs/node.ini:/etc/my.cnf
    networks:
      - mysql_cluster

    # https://docs.docker.com/reference/compose-file/services/#restart
    #restart: on-failure

  mysql-server:
    image: obulka/mysql-cluster
    depends_on:
      - "management"
      - "data1"
      - "data2"
    command: mysqld --ndb-nodeid=4
    volumes:
      - ./configs/node.ini:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: my-super-puper-password
      MYSQL_PASSWORD: my-super-password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myapp

    ports:
      - 3306:3306
    networks:
      - mysql_cluster

networks:
  mysql_cluster:
    driver: bridge

