version: '3'
services:
  mysql-shard1:
    image: mysql:latest
    container_name: mysql-shard1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shard1db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    #volumes:
      # - ./shard1_data:/var/lib/mysql
    networks:
      - mysql-network

  mysql-shard2:
    image: mysql:latest
    container_name: mysql-shard2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shard2db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    #volumes:
      # - ./shard2_data:/var/lib/mysql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge


